export const routes = {
    home: {url: '/', label: 'Home'},
    menu: {url: '/menu', label: 'Menu'},
    about: {url: '/#about', label: 'About'},
    contact: {url: '/#contact', label: 'Contact'},
    login: {url: '/login', label: 'Login'},
    register: {url: '/register', label: 'Register'},
    logout: {url: '/api/auth/signout', label: 'Logout'},
    profile: {url: '/profile', label: 'Profile'},
    categories: {url: '/categories', label: 'Categories'},
    menu_item: {url: '/menu-items', label: 'Menu Items'},
    users: {url: '/users', label: 'Users'},
    my_orders: {url: '/my-orders', label: 'My Orders'},
    all_orders: {url: '/all-orders', label: 'All Orders'},
}