import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "@/components/organisms";
import { Toaster } from "react-hot-toast";
import { AppProvider } from "@/components/AppContext";
import { ScrollToTopButton } from "@/components/molecules";

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${roboto.className}`}>
        <main>
          <AppProvider>
            <Toaster />
            <Header />
            <div className="min-h-[450px] mx-4">
              {children}
              <ScrollToTopButton />
            </div>
            <Footer />
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
